// const BASE_URL = 'http://localhost:8000'
const BASE_URL = 'http://192.168.0.34:8002'
const API_URL = '/api'
export const LOGIN_URL = BASE_URL + '/oauth/token'
export const USER_URL = BASE_URL + API_URL + '/user'
